# TCL File Generated by Component Editor 18.1
# Sat Dec 19 19:02:26 CET 2020
# DO NOT MODIFY


#
# LCD_controller_top "LCD controller" v1.0
# Vassili Cruchet 2020.12.19.19:02:26
# Memory mapped interface to display data read in an external DDR3 memory on an LT24 LCD display.
#

#
# request TCL package from ACDS 16.1
#
package require -exact qsys 16.1


#
# module LCD_controller_top
#
set_module_property DESCRIPTION "Memory mapped interface to display data read in an external DDR3 memory on an LT24 LCD display."
set_module_property NAME LCD_controller_top
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Vassili Cruchet"
set_module_property DISPLAY_NAME "LCD controller"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


#
# file sets
#
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL LCD_controller_top
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file LCD_controller_top.vhd VHDL PATH LCD_controller/LCD_controller_top.vhd TOP_LEVEL_FILE
add_fileset_file AS_registers.vhd VHDL PATH LCD_controller/AS_registers.vhd
add_fileset_file LCD_controller.vhd VHDL PATH LCD_controller/LCD_controller.vhd
add_fileset_file master_control.vhd VHDL PATH LCD_controller/master_control.vhd
add_fileset_file FIFO_LCD.vhd VHDL PATH FIFO/FIFO_LCD.vhd


#
# parameters
#


#
# display items
#


#
# connection point clock
#
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


#
# connection point as
#
add_interface as avalon end
set_interface_property as addressUnits WORDS
set_interface_property as associatedClock clock
set_interface_property as associatedReset reset_sink
set_interface_property as bitsPerSymbol 8
set_interface_property as burstOnBurstBoundariesOnly false
set_interface_property as burstcountUnits WORDS
set_interface_property as explicitAddressSpan 0
set_interface_property as holdTime 0
set_interface_property as linewrapBursts false
set_interface_property as maximumPendingReadTransactions 0
set_interface_property as maximumPendingWriteTransactions 0
set_interface_property as readLatency 0
set_interface_property as readWaitTime 1
set_interface_property as setupTime 0
set_interface_property as timingUnits Cycles
set_interface_property as writeWaitTime 0
set_interface_property as ENABLED true
set_interface_property as EXPORT_OF ""
set_interface_property as PORT_NAME_MAP ""
set_interface_property as CMSIS_SVD_VARIABLES ""
set_interface_property as SVD_ADDRESS_GROUP ""

add_interface_port as AS_address address Input 3
add_interface_port as AS_write write Input 1
add_interface_port as AS_writedata writedata Input 32
add_interface_port as AS_read read Input 1
add_interface_port as AS_readdata readdata Output 32
add_interface_port as AS_waitrequest waitrequest Output 1
set_interface_assignment as embeddedsw.configuration.isFlash 0
set_interface_assignment as embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment as embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment as embeddedsw.configuration.isPrintableDevice 0


#
# connection point am
#
add_interface am avalon start
set_interface_property am addressUnits SYMBOLS
set_interface_property am associatedClock clock
set_interface_property am associatedReset reset_sink
set_interface_property am bitsPerSymbol 8
set_interface_property am burstOnBurstBoundariesOnly false
set_interface_property am burstcountUnits WORDS
set_interface_property am doStreamReads false
set_interface_property am doStreamWrites false
set_interface_property am holdTime 0
set_interface_property am linewrapBursts false
set_interface_property am maximumPendingReadTransactions 0
set_interface_property am maximumPendingWriteTransactions 0
set_interface_property am readLatency 0
set_interface_property am readWaitTime 1
set_interface_property am setupTime 0
set_interface_property am timingUnits Cycles
set_interface_property am writeWaitTime 0
set_interface_property am ENABLED true
set_interface_property am EXPORT_OF ""
set_interface_property am PORT_NAME_MAP ""
set_interface_property am CMSIS_SVD_VARIABLES ""
set_interface_property am SVD_ADDRESS_GROUP ""

add_interface_port am AM_burstcount burstcount Output 7
add_interface_port am AM_address address Output 32
add_interface_port am AM_read read Output 1
add_interface_port am AM_readdatavalid readdatavalid Input 1
add_interface_port am AM_readdata readdata Input 32
add_interface_port am AM_waitrequest waitrequest Input 1


#
# connection point reset_sink
#
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink nReset reset_n Input 1


#
# connection point LT24_interface
#
add_interface LT24_interface conduit end
set_interface_property LT24_interface associatedClock clock
set_interface_property LT24_interface associatedReset ""
set_interface_property LT24_interface ENABLED true
set_interface_property LT24_interface EXPORT_OF ""
set_interface_property LT24_interface PORT_NAME_MAP ""
set_interface_property LT24_interface CMSIS_SVD_VARIABLES ""
set_interface_property LT24_interface SVD_ADDRESS_GROUP ""

add_interface_port LT24_interface LCD_CS_N cs_n Output 1
add_interface_port LT24_interface LCD_RD_N rd_n Output 1
add_interface_port LT24_interface LCD_RS rs Output 1
add_interface_port LT24_interface LCD_WR_N wr_n Output 1
add_interface_port LT24_interface LCD_data d Output 16
